# Generated by Django 5.0.4 on 2024-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tblpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpost',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
