# Generated by Django 5.0.4 on 2024-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tblpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpost',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tblpost',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
