# Generated by Django 5.0.4 on 2024-06-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tblpost_rating_alter_tblpost_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpost',
            name='rating',
        ),
        migrations.CreateModel(
            name='Tblrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_auther_rate', to='app.tbluser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_post_rate', to='app.tblpost')),
            ],
        ),
    ]
